# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "projects/dotfiles"

[settings]

[settings.dots]

# You can have as many dot entry as you want, linking files or directories
alacritty = { source = ".config/alacritty/alacritty.yml", target = ".config/alacritty/alacritty.yml" }

liquidprompt = { source = ".config/liquidpromptrc", target = ".config/liquidpromptrc" }

git = { source = ".gitconfig", target = ".gitconfig" }

i3 = { source = ".config/i3/config", target = ".config/i3/config" }

i3status-rust = { source = ".config/i3status-rust/config.toml", target = ".config/i3status-rust/config.toml" }
 
picom = { source = ".config/picom/picom.conf", target = ".config/picom/picom.conf" }

X = { source = ".Xresources", target = ".Xresources" }
