dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars/vars.toml"]

# Base
[settings.dots]
zsh = { source = "base/zsh", target = ".config/zsh" }

git = { source = "base/git/.gitconfig", target = ".gitconfig" }
helix = { source = "base/helix", target = ".config/helix" }
pacman = { source = "base/pacman", target = ".config/pacman" }

# PC
[profiles.pc]
posthooks = [
  "i3 restart",
  "systemctl --user daemon-reload",
  "systemctl --user enable --now ssh-agent",
]

[profiles.pc.dots]
zshenv = { source = "pc/zshenv", target = ".zshenv" }

ssh-agent-service = { source = "pc/systemd-user/ssh-agent.service", target = ".config/systemd/user/ssh-agent.service" }
xprofile = { source = "pc/xprofile", target = ".xprofile" }

i3 = { source = "pc/i3", target = ".config/i3" }
i3status-rust = { source = "pc/i3status-rust", target = ".config/i3status-rust" }
X11 = { source = "pc/xinitrc", target = ".xinitrc" }
gtk-3.0 = { source = "pc/gtk-3.0", target = ".config/gtk-3.0" }

rofi = { source = "pc/rofi", target = ".config/rofi" }

[profiles.laptop]
extra_profiles = ["pc"]
vars = ["vars/laptop.toml"]

[profiles.desktop]
extra_profiles = ["pc"]
vars = ["vars/desktop.toml"]
