dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars/vars.toml"]

# Base
[settings.dots]
zsh = { source = "base/zsh/zshrc", target = ".zshrc" }

kitty = { source = "base/kitty", target = ".config/kitty" }
git = { source = "base/gitconfig", target = ".gitconfig" }
helix = { source = "base/helix", target = ".config/helix" }

# PC
[profiles.pc.dots]
gtk-3 = { source = "pc/gtk-3.0", target = ".config/gtk-3.0" }
hypr = { source = "pc/hypr", target = ".config/hypr" }
eww = { source = "pc/eww", target = ".config/eww" }
aconfmgr = { source = "pc/aconfmgr", target = ".config/aconfmgr" }

# Laptop
[profiles.laptop]
extra_profiles = ["pc"]
vars = ["vars/laptop.toml"]

# Desktop
[profiles.desktop]
extra_profiles = ["pc"]
vars = ["vars/desktop.toml"]
