[Greeter]
icon-theme-name=Adwaita
draw-grid=false
background=/usr/share/wallpapers/background.png
background-color=#000000
draw-user-backgrounds=true
logo=/home/townload/Downloads/1607458.png
stretch-background-across-monitors=true
