# XDG Setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZRC=$ZDOTDIR/.zshrc

export PATH=~/.bin:$PATH
export CARGO_HOME=$HOME/.cargo
export PATH=~/.cargo/bin:$PATH

export PATH=~/flutter/bin:$PATH

export ROCM_PATH=/opt/rocm
export HSA_OVERRIDE_GFX_VERSION=11.0.0
