# XDG Setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZRC=$ZDOTDIR/.zshrc

export PATH=~/.bin:$PATH
export PATH=~/.cache/cargo/bin:$PATH
export CARGO_HOME=$XDG_CACHE_HOME/cargo

export PATH=~/flutter/bin:$PATH
